#include<stdio.h>
#include "cards.h"

int main(void) {
  card_t firstCard;
  firstCard = card_from_letters('0','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('0','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('0','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('2','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('2','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('2','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('2','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('3','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('3','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('3','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('3','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('4','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('4','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('4','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('4','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('5','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('5','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('5','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('5','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('6','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('6','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('6','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('6','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('7','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('7','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('7','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('7','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('8','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('8','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('8','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('8','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('9','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('9','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('9','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('9','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('A','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('A','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('A','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('A','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('J','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('J','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('J','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('J','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('K','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('K','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('K','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('K','s');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('Q','c');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('Q','d');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('Q','h');
  print_card(firstCard);
  printf("\n");
  firstCard = card_from_letters('Q','s');
  print_card(firstCard);
  printf("\n");
  return 0;
}
